[app]
port=9091
adminport=9092
url_prefix= http://localhost:9091/

[captcha]
# store=memory
store=redis

[redis]
host=127.0.0.1:6379
database=0
username=
password=
pool_size=50

[postgres]
host=127.0.0.1
port=5432
user=postgres
password=123456
dbname=my_url_shortner
max_open_conns=50
max_idle_time=10